api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
#    eager_loading:
#        enabled; true
#    collection:
#        order_parameter_name: '_order'
    collection:
        pagination:
#            enabled: false
            page_parameter_name: _page
            client_enabled: false
            enabled_parameter_name: pagination
            items_per_page: 10
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 100
            partial: false               # Can increase performance if true
            client_partial: true
            partial_parameter_name: 'partial'
    exception_to_status:
        App\Exception\EmptyBodyException: 400