<?php

namespace App\Controller;

use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AdminController as BaseAdminController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * Class UserAdminController
 */
class UserAdminController extends BaseAdminController
{
    /** @var UserPasswordEncoderInterface $encoder */
    private $encoder;

    public function __construct(
        UserPasswordEncoderInterface $encoder
    )
    {
        $this->encoder = $encoder;
    }

    /**
     * @param User $entity
     */
    protected function persistEntity($entity)
    {
        $this->encodeUserPassword($entity);
        parent::persistEntity($entity);
    }

    /**
     * @param User $entity
     */
    protected function updateEntity($entity)
    {
        $this->encodeUserPassword($entity);
        parent::updateEntity($entity); // TODO: Change the autogenerated stub
    }

    /**
     * @param User $entity
     */
    private function encodeUserPassword($entity)
    {
        $entity->setPassword(
            $this->encoder->encodePassword($entity, $entity->getPassword())
        );
    }
}